// /lib/bank.js
// Centralized list of supported countries and banks
// You can easily expand this list (up to 100+ safely)

export const BANKS = {
  "United States": [
    "Bank of America",
    "Chase",
    "Wells Fargo",
    "CitiBank",
    "US Bank",
    "PNC Bank",
  ],
  Canada: ["RBC", "TD Canada Trust", "Scotiabank", "BMO", "CIBC"],
  "United Kingdom": ["HSBC", "Barclays", "Lloyds", "NatWest", "Santander"],
  Nigeria: ["Zenith Bank", "GTBank", "UBA", "Access Bank", "First Bank"],
  Ghana: ["Ecobank", "GCB Bank", "Fidelity Bank Ghana", "Stanbic Ghana"],
  Kenya: ["Equity Bank", "KCB", "Co-operative Bank", "Stanbic Bank Kenya"],
  "South Africa": ["Standard Bank", "FNB", "Nedbank", "Absa", "Capitec"],
  Liberia: ["LBDI", "Ecobank Liberia", "UBA Liberia", "Global Bank Liberia"],
  "United Arab Emirates": [
    "Emirates NBD",
    "Abu Dhabi Commercial Bank",
    "Mashreq Bank",
  ],
  India: ["SBI", "HDFC Bank", "ICICI Bank", "Axis Bank", "Kotak Mahindra"],
  China: [
    "ICBC",
    "China Construction Bank",
    "Agricultural Bank of China",
    "Bank of China",
  ],
  Brazil: ["Itaú", "Bradesco", "Banco do Brasil", "Santander Brasil"],
  Mexico: ["BBVA Bancomer", "Banamex", "Santander Mexico", "Banorte", "Scotiabank Mexico"],
  Argentina: ["Banco Galicia", "Banco Nación", "Banco Santander Río"],
  Chile: ["Banco de Chile", "BancoEstado", "Santander Chile"],
  Colombia: ["Bancolombia", "Banco de Bogotá", "Davivienda"],
  Peru: ["BCP", "Interbank", "BBVA Peru"],
  Ecuador: ["Banco Pichincha", "Banco Guayaquil", "Produbanco"],
  Bolivia: ["Banco Mercantil Santa Cruz", "Banco BISA", "Banco Fassil"],
  Paraguay: ["Banco Itaú Paraguay", "Banco Regional", "BBVA Paraguay"],
  Uruguay: ["Banco República", "Santander Uruguay", "BBVA Uruguay"],
  Panama: ["Banco General", "Banistmo", "Global Bank Panama"],
  CostaRica: ["BAC Credomatic", "Banco Nacional", "Scotiabank Costa Rica"],
  DominicanRepublic: ["Banco Popular", "Scotiabank Dominican Republic", "BHD León"],
  PuertoRico: ["Popular Bank", "Scotiabank Puerto Rico", "FirstBank Puerto Rico"],
  Spain: ["Santander", "BBVA", "CaixaBank", "Banco Sabadell", "ING Spain"],
  Venezuela: ["Banco de Venezuela", "Banesco", "Banco Mercantil", "Banco Provincial"],
  Cuba: ["Banco Metropolitano", "BPA Bank", "Banco Popular de Ahorro"],
  Guatemala: ["Banco Industrial", "Banco G&T Continental", "Banrural"],
  ElSalvador: ["Banco Agrícola", "Scotiabank El Salvador", "Banco Davivienda El Salvador"],
  Honduras: ["Banco Atlántida", "BAC Honduras", "Ficohsa"],
  Nicaragua: ["Banco de la Producción", "BAC Credomatic Nicaragua", "Banco Lafise"],
  EquatorialGuinea: ["Banco de Guinea Ecuatorial", "BGE", "Ecobank Equatorial Guinea"],
  Andorra: ["Banca March", "Andbank", "Crèdit Andorrà"],
  Jamaica: ["NCB Jamaica", "Scotiabank Jamaica", "Sagicor Bank Jamaica"],
  TrinidadTobago: ["Republic Bank", "First Citizens", "Scotiabank Trinidad and Tobago"],
  Barbados: ["CIBC FirstCaribbean", "Republic Bank Barbados", "Scotiabank Barbados"],
  Bahamas: ["Scotiabank Bahamas", "CIBC FirstCaribbean Bahamas", "Royal Bank of Canada Bahamas"],
  Belize: ["Belize Bank", "Scotiabank Belize", "Atlantic Bank"],
  Guyana: ["Republic Bank Guyana", "Bank of Baroda Guyana", "Guyanese Bank"],
  Suriname: ["Hakrinbank", "Republic Bank Suriname"],
  Egypt: ["National Bank of Egypt", "Banque Misr", "CIB Egypt"],
  Morocco: ["Attijariwafa Bank", "BMCE Bank", "Banque Populaire"],
  Tunisia: ["BIAT", "Amen Bank", "UBCI"],
  Algeria: ["Banque Extérieure d’Algérie", "CNEP Bank", "BEA"],
  Turkey: ["Ziraat Bank", "Garanti BBVA", "İşbank"],
  SaudiArabia: ["Al Rajhi Bank", "National Commercial Bank", "SABB"],
  Israel: ["Bank Hapoalim", "Bank Leumi", "Discount Bank"],
  Jordan: ["Arab Bank", "Cairo Amman Bank", "Housing Bank"],
  Lebanon: ["Bank Audi", "Blom Bank", "Byblos Bank"],
  Oman: ["Bank Muscat", "Bank Dhofar", "Oman Arab Bank"],
  Bahrain: ["National Bank of Bahrain", "Ahli United Bank", "Bank of Bahrain and Kuwait"],
  Qatar: ["QNB", "Doha Bank", "Commercial Bank of Qatar"],
  Kuwait: ["NBK", "Gulf Bank", "Burgan Bank"],
  Iraq: ["Rafidain Bank", "Trade Bank of Iraq", "Bank of Baghdad"],
  Iran: ["Bank Melli", "Tejarat Bank", "Saderat Bank"],
  Pakistan: ["HBL", "UBL", "MCB", "Allied Bank"],
  Afghanistan: ["Azizi Bank", "AIB", "Pashtany Bank"],
  Kazakhstan: ["Halyk Bank", "Kaspi Bank", "Jusan Bank"],
  Uzbekistan: ["Asaka Bank", "UzPromstroybank", "Kapitalbank"],
  Kyrgyzstan: ["Optima Bank", "Demir Kyrgyz International Bank", "Bakai Bank"],
  Tajikistan: ["Orienbank", "TajikSodrBank", "Bank Eskhata"],
  Turkmenistan: ["Turkmenistan Bank", "Halk Bank", "Rysgal Bank"],
  Azerbaijan: ["International Bank of Azerbaijan", "Kapital Bank", "Bank Respublika"],
  Armenia: ["Ameriabank", "ACBA Bank", "Ardshinbank"],
  Georgia: ["TBC Bank", "Bank of Georgia", "Liberty Bank"],
  Qatar: ["QNB", "Doha Bank", "Commercial Bank of Qatar"],
  Kuwait: ["NBK", "Gulf Bank", "Burgan Bank"],
  Singapore: ["DBS Bank", "OCBC", "UOB"],
  Malaysia: ["Maybank", "CIMB", "RHB Bank"],
  Indonesia: ["Bank Mandiri", "BCA", "BNI"],
  Philippines: ["BDO", "Metrobank", "LandBank"],
  Thailand: ["Bangkok Bank", "Kasikorn Bank", "SCB"],
  Japan: ["MUFG Bank", "SMBC", "Mizuho Bank"],
  SouthKorea: ["Kookmin Bank", "Hana Bank", "Woori Bank"],
  Australia: ["Commonwealth Bank", "Westpac", "ANZ", "NAB"],
  NewZealand: ["ASB", "BNZ", "Westpac NZ", "Kiwibank"],
  France: ["BNP Paribas", "Société Générale", "Crédit Agricole"],
  Germany: ["Deutsche Bank", "Commerzbank", "Sparkasse", "ING"],
  Ireland: ["AIB", "Bank of Ireland", "Permanent TSB"],
  Portugal: ["Caixa Geral de Depósitos", "Novo Banco", "Millennium bcp"],
  Iceland: ["Landsbankinn", "Íslandsbanki", "Arion Bank"],
  Estonia: ["LHV", "Swedbank Estonia", "SEB Estonia"],
  Latvia: ["Citadele Banka", "SEB Latvia", "Swedbank Latvia"],
  Lithuania: ["Swedbank Lithuania", "SEB Lithuania", "Luminor"],
  Italy: ["UniCredit", "Intesa Sanpaolo", "Monte dei Paschi di Siena"],
  Spain: ["Santander", "BBVA", "CaixaBank"],
  Netherlands: ["ING", "Rabobank", "ABN AMRO"],
  Belgium: ["BNP Paribas Fortis", "KBC", "Belfius", "ING Belgium"],
  Austria: ["Erste Group", "Raiffeisen Bank International", "UniCredit Bank Austria", "BAWAG P.S.K."],
  Luxembourg: ["BCEE", "ING Luxembourg", "Banque et Caisse d'Épargne de l'État", "Société Générale Luxembourg"],
  Malta: ["Bank of Valletta", "HSBC Malta", "BOV", "Banif Bank Malta"],
  Switzerland: ["UBS", "Credit Suisse", "Julius Baer"],
  Sweden: ["Swedbank", "SEB", "Nordea"],
  Norway: ["DNB", "SpareBank 1", "Nordea"],
  Denmark: ["Danske Bank", "Nordea Denmark", "Jyske Bank"],
  Finland: ["Nordea Finland", "OP Financial Group"],
  Poland: ["PKO Bank Polski", "Santander Poland", "mBank"],
  CzechRepublic: ["Česká spořitelna", "Komerční banka", "Moneta Money Bank"],
  Slovakia: ["Slovenská sporiteľňa", "VÚB Banka", "Prima banka"],
  Slovenia: ["Nova KBM", "NLB", "Addiko Bank Slovenia"],
  Croatia: ["Privredna banka Zagreb", "Raiffeisenbank Austria Croatia", "Zagrebačka banka"],
  Hungary: ["OTP Bank", "K&H Bank", "UniCredit Hungary"],
  Romania: ["BCR", "BRD", "Raiffeisen Bank Romania"],
  Bulgaria: ["UniCredit Bulbank", "DSK Bank", "Postbank Bulgaria"],
  Serbia: ["Raiffeisen Bank Srbije", "OTP banka Srbija", "Komercijalna banka"],
  Ukraine: ["PrivatBank", "Oschadbank", "Ukreximbank"],
  SouthSudan: ["KCB South Sudan", "Equity Bank South Sudan"],
  SierraLeone: ["Rokel Commercial Bank", "Sierra Leone Commercial Bank"],
  Cameroon: ["Afriland First Bank", "UBA Cameroon", "BICEC"],
  Tanzania: ["CRDB Bank", "NMB Bank", "Stanbic Bank Tanzania"],
  Uganda: ["Stanbic Bank Uganda", "Centenary Bank", "dfcu Bank"],
  Rwanda: ["Bank of Kigali", "Equity Bank Rwanda", "I&M Bank Rwanda"],
  Zambia: ["Zanaco", "Stanbic Bank Zambia", "Absa Bank Zambia"],
  Zimbabwe: ["CBZ Bank", "Stanbic Zimbabwe", "Steward Bank"],
  Mozambique: ["BCI", "Millennium BIM", "Standard Bank Mozambique"],
  Botswana: ["First Capital Bank", "Stanbic Bank Botswana", "Absa Botswana"],
  Namibia: ["Bank Windhoek", "FNB Namibia", "Standard Bank Namibia"],
  Angola: ["BAI", "BFA", "Banco Económico"],
  Seychelles: ["MCB Seychelles", "Barclays Seychelles"],
  Mauritius: ["MCB", "SBM Bank", "ABC Banking"],
  Cyprus: ["Bank of Cyprus", "Hellenic Bank"],
  Greece: ["Alpha Bank", "Eurobank", "Piraeus Bank"],
  Israel: ["Bank Hapoalim", "Bank Leumi", "Discount Bank"],
  Pakistan: ["HBL", "UBL", "MCB", "Allied Bank"],
  Bangladesh: ["BRAC Bank", "Dutch-Bangla Bank", "Sonali Bank"],
  SriLanka: ["Bank of Ceylon", "Commercial Bank", "Peoples Bank"],
  Nepal: ["Nabil Bank", "Nepal Investment Bank", "Siddhartha Bank"],
  Afghanistan: ["Azizi Bank", "AIB", "Pashtany Bank"],
  Iran: ["Bank Melli", "Tejarat Bank", "Saderat Bank"],
  Iraq: ["Rafidain Bank", "Trade Bank of Iraq", "Bank of Baghdad"],
  Lebanon: ["Bank Audi", "Blom Bank", "Byblos Bank"],
  Jordan: ["Arab Bank", "Cairo Amman Bank", "Housing Bank"],
  Oman: ["Bank Muscat", "Bank Dhofar", "Oman Arab Bank"],
  Bahrain: ["National Bank of Bahrain", "Ahli United Bank"],
  Vietnam: ["Vietcombank", "Techcombank", "BIDV"],
  Laos: ["BCEL", "LaoViet Bank"],
  Cambodia: ["ABA Bank", "Acleda Bank", "Canadia Bank"],
  Myanmar: ["KBZ Bank", "AYA Bank", "CB Bank"],
  Mongolia: ["Khan Bank", "Golomt Bank", "Trade and Development Bank"],
  Kazakhstan: ["Halyk Bank", "Kaspi Bank"],
  Uzbekistan: ["Asaka Bank", "UzPromstroybank"],
  Georgia: ["TBC Bank", "Bank of Georgia"],
  Armenia: ["Ameriabank", "ACBA Bank"],
  Azerbaijan: ["International Bank of Azerbaijan", "Kapital Bank"],
  Belarus: ["Belarusbank", "Priorbank"],
  Venezuela: ["Banco de Venezuela", "Banesco", "Banco Mercantil"],
  SouthAfrica: ["Standard Bank", "FNB", "Absa", "Capitec"],
  Botswana: ["First Capital Bank", "Stanbic Bank Botswana", "Absa Botswana"],
  Namibia: ["Bank Windhoek", "FNB Namibia", "Standard Bank Namibia"],
  Zambia: ["Zanaco", "Stanbic Bank Zambia", "Absa Bank Zambia"],
  Zimbabwe: ["CBZ Bank", "Stanbic Zimbabwe", "Steward Bank"],
  Mozambique: ["BCI", "Millennium BIM", "Standard Bank Mozambique"],
  Angola: ["BAI", "BFA", "Banco Económico"],
  Seychelles: ["MCB Seychelles", "Barclays Seychelles"],
  Mauritius: ["MCB", "SBM Bank", "ABC Banking"],
  Cyprus: ["Bank of Cyprus", "Hellenic Bank"],
  Greece: ["Alpha Bank", "Eurobank", "Piraeus Bank"],
  Malta: ["Bank of Valletta", "HSBC Malta", "BOV", "Banif Bank Malta"],
  Romania: ["BCR", "BRD", "Raiffeisen Bank Romania"],
  Bulgaria: ["UniCredit Bulbank", "DSK Bank", "Postbank Bulgaria"],
  Serbia: ["Raiffeisen Bank Srbije", "OTP banka Srbija", "Komercijalna banka"],
  Croatia: ["Privredna banka Zagreb", "Raiffeisenbank Austria Croatia", "Zagrebačka banka"],
  Slovakia: ["Slovenská sporiteľňa", "VÚB Banka", "Prima banka"],
  Slovenia: ["Nova KBM", "NLB", "Addiko Bank Slovenia"],
  CzechRepublic: ["Česká spořitelna", "Komerční banka", "Moneta Money Bank"],
  Hungary: ["OTP Bank", "K&H Bank", "UniCredit Hungary"],
  Poland: ["PKO Bank Polski", "Santander Poland", "mBank"],
  Ukraine: ["PrivatBank", "Oschadbank", "Ukreximbank"],
};
